provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  contributors-page:
    lang: node
    handler: ./contributors-page
    image: kenfdev/contributors-page:0.9.1
    environment:
      content_type: text/html
